provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  csharp-func:
    lang: csharp
    handler: ./csharp-func
    image: viveksyngh/csharp-func:latest
  go-hello-world:
    lang: go
    handler: ./go-hello-world
    image: viveksyngh/go-hello-world:latest
  golang-http-func:
    lang: golang-http
    handler: ./golang-http-func
    image: viveksyngh/golang-http-func:latest
  java-func:
    lang: java8
    handler: ./java-func
    image: viveksyngh/java-func:latest
  node-func:
    lang: node
    handler: ./node-func
    image: viveksyngh/node-func:latest
  python-hello-word:
    lang: python
    handler: ./python-hello-word
    image: viveksyngh/python-hello-word:latest
  python3-func:
    lang: python3
    handler: ./python3-func
    image: viveksyngh/python3-func:latest
  ruby-func:
    lang: ruby
    handler: ./ruby-func
    image: viveksyngh/ruby-func:latest
